# Generated by Django 2.0.5 on 2018-09-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllist',
            name='actual_target',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
