# Generated by Django 2.2.1 on 2019-05-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_redirects', '0003_auto_20190528_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urllist',
            name='protocol',
        ),
    ]
