# Generated by Django 2.0.5 on 2018-09-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkredirects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllist',
            name='target_url',
            field=models.URLField(default=''),
        ),
    ]
