# Generated by Django 2.0.5 on 2018-09-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkredirects', '0002_urllist_target_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urllist',
            name='actual_target',
            field=models.URLField(default=''),
        ),
    ]
