# Generated by Django 2.0.5 on 2018-09-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkredirects', '0003_urllist_actual_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.FloatField(default=0.0)),
            ],
        ),
    ]
